version: '3'
services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./api:/home/api/public_html
      - ./web:/home/node/public_html
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - laranet

  mysql:
    image: mariadb:10.6
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laranet

  php:
    build:
      context: ./api
      dockerfile: ../dockerfiles/php/Dockerfile
    container_name: api
    volumes:
      - ./api:/home/api/public_html
    networks:
      - laranet

  web:
    build:
      context: ./web
      dockerfile: ../dockerfiles/web/Dockerfile
    volumes:
      - ./web:/home/node/public_html
    networks:
      - laranet

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laranet

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer
    volumes:
      - ./api:/home/api/public_html
    working_dir: /home/api/public_html
    depends_on:
      - php
    user: laranet
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laranet

  npm:
    image: node:17-alpine
    container_name: npm
    volumes:
#      - ./api:/home/api/public_html
      - ./web:/home/node/public_html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /home/node/public_html
    entrypoint: ['npm']
    networks:
      - laranet

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php/Dockerfile
    container_name: artisan
    volumes:
      - ./api:/home/api/public_html
    depends_on:
      - mysql
    working_dir: /home/api/public_html
    entrypoint: ['php', '/home/api/public_html/artisan']
    networks:
      - laranet

  git:
    image: alpine/git
    container_name: git
    volumes:
    - $HOME/.ssh:/root/.ssh
    - ./:/git
    working_dir: /git
    networks:
      - laranet

networks:
  laranet:
    driver: bridge